# Uncomment the next line to define a global platform for your project
# platform :ios, '14.0'

target 'WakeMe' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WakeMe
pod 'Charts'
pod 'TinyConstraints'

  target 'WakeMeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WakeMeUITests' do
    # Pods for testing
  end

end

